version: '3.8'

services:
  postgres_test:
    image: postgres:15
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_medicine_db
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    networks:
      - test-network

volumes:
  test_postgres_data:

networks:
  test-network:
    driver: bridge